config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'pages#home'

  get '/:id', to: 'urls#show', as: :show_url
  post '/urls', to: 'urls#create', as: :urls

  get '*unmatched_route', to: 'application#not_found'
end

app/models/admin_user.rb
# frozen_string_literal: true

# Admin User Model
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

# Application Record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
# frozen_string_literal: true

# Url Model
class Url < ApplicationRecord
  include Hashid::Rails

  validates :url, presence: true, format: { with: URI::DEFAULT_PARSER.make_regexp(%w[http https]) }

  def available?
    Time.zone.today - 7 <= Date.parse(created_at.localtime.to_s, '%d-%m-%Y')
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Application Controller
class ApplicationController < ActionController::Base
  protect_from_forgery

  def not_found
    render 'urls/show'
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# Pages Controller
class PagesController < ApplicationController
  def home
    @url = Url.new
  end
end

app/controllers/urls_controller.rb
# frozen_string_literal: true

# Url Controller
class UrlsController < ApplicationController
  before_action :set_url, only: :show

  def create
    @url = Url.new(url_params)
    if @url.save
      render :create, status: :created
    else
      render :error, status: :unprocessable_entity
    end
  end

  def show
    if @url&.available?
      redirect_to @url.url
    else
      render :show
    end
  end

  private

  def url_params
    params.require(:url).permit(:url)
  end

  def set_url
    @url = Url.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Application Helper
module ApplicationHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

# Pages Helper
module PagesHelper
end

app/helpers/urls_helper.rb
# frozen_string_literal: true

# Urls Helper
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1">
  </head>

  <body class="flex flex-col h-full">
    <%= render partial: 'partials/header' %>

    <%= yield %>

    <%= render partial: 'partials/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="flex-1 bg-blue-200 w-full items-center">
  <div class="leading-loose">
    <div class="max-w-xl mx-auto m-4 p-10 bg-blue-100 rounded shadow-xl">
      <h3 class="text-gray-800 text-2xl uppercase font-medium text-center mb-5">Short url generator</h3>

      <%= simple_form_for @url, remote: true do |f| %>
        <div class="md:flex md:items-start mb-4">
          <div class="md:w-1/6">
            <label class="block text-gray-500 font-bold md:text-right mb-1 mt-0 md:mb-0 md:mt-1 pr-4 uppercase text-lg" for="url_url">
              Url
            </label>
          </div>
          <div class="md:w-5/6">
            <%= f.input :url, input_html: {
                                class: 'bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500',
                                placeholder: 'https://www.example.com'
                              },
                              required: true,
                              label: false,
                              hint: '*Take in mind the url will be available just for a week',
                              hint_html: { class: 'text-sm' } %>
            <p class="bg-red-500 text-white border-red-800 rounded px-3 hidden" id="error_url">Url is invalid</p>
          </div>
        </div>

        <div class="mt-4 text-center">
          <button class="px-4 py-1 text-white font-light tracking-wider bg-gray-900 hover:bg-gray-800 rounded" type="submit">Get short url</button>
        </div>
      <% end %>
    </div>

    <div id="div_short_url" class="max-w-xl mx-auto m-4 p-5 bg-blue-100 rounded shadow-xl hidden">
      <h3 class="text-gray-800 text-2xl uppercase font-medium text-center mb-5">Url Generated</h3>

      <div class="w-full bg-gray-900 text-gray-300 rounded px-1 flex cursor-pointer" onclick="copyToClipboard()">
        <p class="py-3 w-9/12" id="short_url"></p>
        <script>
          function copyToClipboard() {
            const text = document.getElementById('short_url');
            const selection = window.getSelection();
            const range = document.createRange();
            range.selectNodeContents(text);
            selection.removeAllRanges();
            selection.addRange(range);
            document.execCommand('copy');
            selection.removeAllRanges();

            let span_copy = document.getElementById('span_copy');
            span_copy.innerHTML = 'Copied!';
            setTimeout(() => {
              span_copy.innerHTML = 'Click to Copy';
            }, 5000)
          }
        </script>
        <span id="span_copy" class="w-3/12 h-5 uppercase text-xs font-thin float-right mt-1 text-center bg-white text-black rounded">Click to Copy</span>
      </div>
    </div>
  </div>
</div>

app/views/partials/_footer.html.erb
<footer class="w-full bg-blue-400 text-center border-t border-grey p-4 pin-b">
  URLSHORTENER | Made with 💙 by <a href="https://github.com/dmunoz-10" target="_blank">dmunoz-10</a>
</footer>

app/views/partials/_header.html.erb
<div class="w-full text-gray-700 bg-blue-400 dark-mode:text-gray-200 dark-mode:bg-gray-800">
  <div class="flex flex-col max-w-screen-xl px-4 mx-auto justify-between flex-row md:px-6 lg:px-8">
    <div class="p-4 flex flex-row items-center justify-between">
      <a href="/" class="text-lg font-semibold tracking-widest text-gray-900 uppercase rounded-lg dark-mode:text-white focus:outline-none focus:shadow-outline">
        UrlShortener
      </a>
      <a
        class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline"
        href="https://github.com/dmunoz-10/url-shortener"
        target="_blank"
      >
        Github
      </a>
    </div>
  </div>
</div>

app/views/urls/create.js.erb
function created() {
  let short_url = document.getElementById('short_url');
  short_url.innerHTML = '<%= show_url_url @url %>';

  let url_url = document.getElementById('url_url');
  url_url.value = '';
  url_url.classList.remove('bg-red-400', 'border-red-700', 'text-white');

  let div_short_url = document.getElementById('div_short_url');
  div_short_url.classList.remove('hidden');

  let error_url = document.getElementById('error_url');
  error_url.classList.add('hidden');
}

created();

app/views/urls/error.js.erb
function error() {
  let url_url = document.getElementById('url_url');
  url_url.classList.add('bg-red-400', 'border-red-700', 'text-white');

  let error_class = 'hidden';
  let error_url = document.getElementById('error_url');
  error_url.classList.remove(error_class);

  let short_url = document.getElementById('short_url');
  short_url.innerHTML = '';

  let div_short_url = document.getElementById('div_short_url');
  div_short_url.classList.add('hidden');
}

error();

app/views/urls/show.html.erb
<div class="flex-1 w-full">
  <div class="p-8">
    <div class="bg-white rounded-lg shadow-xl">
      <div class="p-16">
        <div class="w-full text-center">
          <%= image_tag 'worried_panda.gif', style: 'height:200px;width:200px;', class: 'mx-auto' %>
        </div>
        <div class="mt-4 text-center">
          <h1 class="font-bold text-lg text-gray-700 mb-1">Sorry!</h1>
          <p class="text-gray-600 mb-6">It seems the url is expired or invalid (or maybe the page you were looking for doesn't exist)</p>
          <%= link_to 'Go Home', root_path, class: 'bg-blue-500 hover:bg-blue-400 text-white rounded-full px-12 py-3 shadow-xl focus:outline-none' %>
        </div>
      </div>
    </div>
  </div>
</div>